blueprint:
  name: "Tuya TS0042 (2 кнопки, ZHA) универсальный (с логом)"
  description: >
    Универсальный blueprint для переключателя Tuya TS0042 (2 кнопки, ZHA, zha_event).
    Поддерживает одиночное, двойное и долгое нажатие для левой (endpoint_id = 1)
    и правой (endpoint_id = 2) кнопок.
    В каждой ветке есть лог-уведомление для отладки.

  domain: automation

  input:
    switch_ieee:
      name: "Переключатель (TS0042, ZHA)"
      description: "Выберите устройство TS0042, подключённое через ZHA"
      selector:
        device:
          integration: zha

    left_single_action:
      name: "Левая кнопка — одиночное нажатие"
      default: []
      selector:
        action: {}

    left_double_action:
      name: "Левая кнопка — двойное нажатие"
      default: []
      selector:
        action: {}

    left_long_action:
      name: "Левая кнопка — долгое нажатие"
      default: []
      selector:
        action: {}

    right_single_action:
      name: "Правая кнопка — одиночное нажатие"
      default: []
      selector:
        action: {}

    right_double_action:
      name: "Правая кнопка — двойное нажатие"
      default: []
      selector:
        action: {}

    right_long_action:
      name: "Правая кнопка — долгое нажатие"
      default: []
      selector:
        action: {}

mode: restart
max_exceeded: silent

variables:
  switch_ieee: !input switch_ieee

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: !input switch_ieee

action:
  - variables:
      endpoint_id: "{{ trigger.event.data.endpoint_id | int }}"
      command: "{{ trigger.event.data.command }}"
      press_type: >
        {% if command == 'remote_button_short_press' %}
          single
        {% elif command == 'remote_button_double_press' %}
          double
        {% elif command == 'remote_button_long_press' %}
          long
        {% else %}
          unknown
        {% endif %}

  - choose:

      # ---------- Левая кнопка (endpoint_id = 1) ----------

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 1 and press_type == 'single' }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "TS0042"
              message: "Левая кнопка, одиночное нажатие. command={{ command }}"
          - service: system_log.write
            data:
              level: warning
              message: "TS0042: left single, command={{ command }}, data={{ trigger.event.data | tojson }}"
          - choose: []
          - sequence: !input left_single_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 1 and press_type == 'double' }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "TS0042"
              message: "Левая кнопка, двойное нажатие. command={{ command }}"
          - service: system_log.write
            data:
              level: warning
              message: "TS0042: left double, command={{ command }}, data={{ trigger.event.data | tojson }}"
          - choose: []
          - sequence: !input left_double_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 1 and press_type == 'long' }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "TS0042"
              message: "Левая кнопка, долгое нажатие. command={{ command }}"
          - service: system_log.write
            data:
              level: warning
              message: "TS0042: left long, command={{ command }}, data={{ trigger.event.data | tojson }}"
          - choose: []
          - sequence: !input left_long_action

      # ---------- Правая кнопка (endpoint_id = 2) ----------

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 2 and press_type == 'single' }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "TS0042"
              message: "Правая кнопка, одиночное нажатие. command={{ command }}"
          - service: system_log.write
            data:
              level: warning
              message: "TS0042: right single, command={{ command }}, data={{ trigger.event.data | tojson }}"
          - choose: []
          - sequence: !input right_single_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 2 and press_type == 'double' }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "TS0042"
              message: "Правая кнопка, двойное нажатие. command={{ command }}"
          - service: system_log.write
            data:
              level: warning
              message: "TS0042: right double, command={{ command }}, data={{ trigger.event.data | tojson }}"
          - choose: []
          - sequence: !input right_double_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 2 and press_type == 'long' }}"
        sequence:
          - service: persistent_notification.create
            data:
              title: "TS0042"
              message: "Правая кнопка, долгое нажатие. command={{ command }}"
          - service: system_log.write
            data:
              level: warning
              message: "TS0042: right long, command={{ command }}, data={{ trigger.event.data | tojson }}"
          - choose: []
          - sequence: !input right_long_action
