blueprint:
  name: "DROZD - Tuya TS0042 (2 button, ZHA) universal"
  description: >
    Universal Blueprint for Tuya TS0042 (2-button switch, ZHA).
    Supports single, double and long press for left (endpoint 1) and right (endpoint 2) buttons.
    All actions are configurable: you can call any services, switch scenes in a cycle, etc.
  domain: automation
  input:
    switch_ieee:
      name: "Switch (TS0042, ZHA)"
      description: "Select TS0042 device paired via ZHA"
      selector:
        device:
          integration: zha

    # ---------------- BASIC ACTIONS ----------------

    left_single_action:
      name: "Left button - single press"
      description: "Any actions for left button single press"
      default: []
      selector:
        action: {}

    left_double_action:
      name: "Left button - double press"
      description: "Any actions for left button double press"
      default: []
      selector:
        action: {}

    left_long_action:
      name: "Left button - long press"
      description: "Any actions for left button long press"
      default: []
      selector:
        action: {}

    right_single_action:
      name: "Right button - single press"
      description: "Any actions for right button single press"
      default: []
      selector:
        action: {}

    right_double_action:
      name: "Right button - double press"
      description: "Any actions for right button double press"
      default: []
      selector:
        action: {}

    right_long_action:
      name: "Right button - long press"
      description: "Any actions for right button long press"
      default: []
      selector:
        action: {}

    # ---------------- UNIVERSAL SCENE CYCLE ----------------

    cycle_enabled:
      name: "Enable scene cycle"
      description: >
        Enables universal scene cycle mechanism.
        If disabled, the settings below are ignored.
      default: false
      selector:
        boolean: {}

    cycle_trigger_button:
      name: "Button to trigger scene cycle"
      description: >
        Which button will trigger scene cycle.
        Left = endpoint 1, right = endpoint 2.
      default: left
      selector:
        select:
          options:
            - label: "Left button (endpoint 1)"
              value: left
            - label: "Right button (endpoint 2)"
              value: right

    cycle_trigger_press_type:
      name: "Press type for scene cycle"
      description: "Which gesture to use for scene cycle (single/double/long press)."
      default: double
      selector:
        select:
          options:
            - label: "Single press"
              value: single
            - label: "Double press"
              value: double
            - label: "Long press"
              value: long

    cycle_scenes:
      name: "Scenes list for cycle"
      description: >
        Select scenes in the order you want to cycle through.
      default: []
      selector:
        target:
          entity:
            domain: scene
            multiple: true

    cycle_index_helper:
      name: "input_number to store scene index"
      description: >
        Select input_number (min=0, max=N-1) that stores current scene index.
      default:
      selector:
        entity:
          domain: input_number

mode: restart
max_exceeded: silent

variables:
  switch_ieee: !input switch_ieee
  cycle_enabled: !input cycle_enabled
  cycle_trigger_button: !input cycle_trigger_button
  cycle_trigger_press_type: !input cycle_trigger_press_type
  cycle_scenes: !input cycle_scenes
  cycle_index_helper: !input cycle_index_helper

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: !input switch_ieee

action:
  - variables:
      endpoint_id: "{{ trigger.event.data.endpoint_id | int }}"
      command: "{{ trigger.event.data.command }}"
      press_type: >
        {% if command == 'remote_button_short_press' %}
          single
        {% elif command == 'remote_button_double_press' %}
          double
        {% elif command == 'remote_button_long_press' %}
          long
        {% else %}
          unknown
        {% endif %}
      button: >
        {% if endpoint_id == 1 %}
          left
        {% elif endpoint_id == 2 %}
          right
        {% else %}
          unknown
        {% endif %}

  - choose:

      # ---------- BASIC BUTTON ACTIONS ----------

      # Left button
      - conditions:
          - condition: template
            value_template: "{{ button == 'left' and press_type == 'single' }}"
        sequence: !input left_single_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'left' and press_type == 'double' }}"
        sequence: !input left_double_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'left' and press_type == 'long' }}"
        sequence: !input left_long_action

      # Right button
      - conditions:
          - condition: template
            value_template: "{{ button == 'right' and press_type == 'single' }}"
        sequence: !input right_single_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'right' and press_type == 'double' }}"
        sequence: !input right_double_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'right' and press_type == 'long' }}"
        sequence: !input right_long_action

      # ---------- UNIVERSAL SCENE CYCLE ----------

      - conditions:
          - condition: template
            value_template: >
              {{ cycle_enabled
                 and button == cycle_trigger_button
                 and press_type == cycle_trigger_press_type
                 and (cycle_scenes.entity_id | count) > 0
                 and cycle_index_helper is not none }}
        sequence:
          - variables:
              scenes_list: "{{ cycle_scenes.entity_id }}"
              max_index: "{{ (scenes_list | count) - 1 }}"
              current_index: "{{ states(cycle_index_helper) | int(0) }}"
              next_index: >
                {% if current_index >= max_index %}
                  0
                {% else %}
                  {{ current_index + 1 }}
                {% endif %}
          - service: scene.turn_on
            target:
              entity_id: "{{ scenes_list[next_index | int] }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ cycle_index_helper }}"
            data:
              value: "{{ next_index }}"
