blueprint:
  name: "DROZD Light auto v1 - Освещение по движению/присутствию — день/ночь, сцены, солнце/расписание, смещение, ручной таймаут, гибкая деактивация (сцена только при первом включении)"
  description: >
    Блупринт включает свет по движению и выключает по таймауту (раздельно для дня/ночи).
    Ночной режим: отключено / солнце / солнце со смещением / расписание. Можно отключить авто-включение/выключение отдельно для дня и ночи.
    Сцены день/ночь применяются ТОЛЬКО при ПЕРВОМ включении света после смены режима (ночь/день).
    Для этого используются два помощника (input_boolean) — флаги ожидания применения сцен:
    - Флаг ночной сцены: устанавливается при переходе в ночь, сбрасывается при первом включении и применении ночной сцены.
    - Флаг дневной сцены: аналогично для перехода в день.
    ВНИМАНИЕ: создайте два помощника input_boolean в Home Assistant и укажите их в параметрах:
      • input_boolean.night_scene_pending
      • input_boolean.day_scene_pending

  domain: automation

  input:
    motion_sensors:
      name: "Датчики движения/присутствия"
      description: "Один или несколько binary_sensor (state 'on' = движение/присутствие)."
      selector:
        entity:
          domain: binary_sensor
          multiple: true

    target_entities:
      name: "Целевые свет/выключатели"
      description: "Световые устройства (light) и/или выключатели (switch), которые нужно управлять."
      selector:
        target:
          entity:
            domain:
              - light
              - switch

    manual_entities:
      name: "Сущности для отслеживания ручного включения"
      description: "Конкретные light/switch для авто-выключения после ручного включения. Можно оставить пустым."
      selector:
        entity:
          domain:
            - light
            - switch
          multiple: true

    # ФЛАГИ «сцена ожидает применения» — обязательно укажите существующие input_boolean
    night_scene_pending_flag:
      name: "Флаг ожидания НОЧНОЙ сцены (input_boolean)"
      description: "Помощник input_boolean, который будет устанавливаться при начале ночи и сбрасываться после первого применения ночной сцены."
      selector:
        entity:
          domain: input_boolean

    day_scene_pending_flag:
      name: "Флаг ожидания ДНЕВНОЙ сцены (input_boolean)"
      description: "Помощник input_boolean, который будет устанавливаться при начале дня и сбрасываться после первого применения дневной сцены."
      selector:
        entity:
          domain: input_boolean

    day_timeout_seconds:
      name: "Таймаут авто-выключения ДНЁМ (сек)"
      description: "Сколько секунд ждать без движения перед выключением днём."
      default: 180
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
          mode: box

    night_timeout_seconds:
      name: "Таймаут авто-выключения НОЧЬЮ (сек)"
      description: "Сколько секунд ждать без движения перед выключением ночью."
      default: 600
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
          mode: box

    enable_night_mode:
      name: "Включить ночной режим"
      description: "Если выключено — всегда считается день."
      default: true
      selector:
        boolean: {}

    night_mode_source:
      name: "Источник ночного режима"
      description: "Как определяется ночь: солнце / солнце со смещением / расписание."
      default: sun
      selector:
        select:
          options:
            - label: "Солнце (ниже/выше горизонта)"
              value: sun
            - label: "Солнце со смещением"
              value: sun_offset
            - label: "Расписание (начало/конец)"
              value: schedule

    sunset_offset_minutes:
      name: "Смещение от заката (мин)"
      description: "Отрицательное = до заката, положительное = после (для режима со смещением)."
      default: -60
      selector:
        number:
          min: -720
          max: 720
          unit_of_measurement: minutes
          mode: box

    sunrise_offset_minutes:
      name: "Смещение от восхода (мин)"
      description: "Отрицательное = до восхода, положительное = после (для режима со смещением)."
      default: 60
      selector:
        number:
          min: -720
          max: 720
          unit_of_measurement: minutes
          mode: box

    schedule_night_start:
      name: "Начало ночи (расписание)"
      description: "Используется при night_mode_source = schedule."
      default: "22:00:00"
      selector:
        time: {}

    schedule_night_end:
      name: "Конец ночи (расписание)"
      description: "Используется при night_mode_source = schedule."
      default: "06:30:00"
      selector:
        time: {}

    day_scene:
      name: "Дневная сцена"
      description: "Активируется при первом включении после перехода в день (и только один раз)."
      selector:
        entity:
          domain: scene
          multiple: false

    night_scene:
      name: "Ночная сцена"
      description: "Активируется при первом включении после перехода в ночь (и только один раз)."
      selector:
        entity:
          domain: scene
          multiple: false

    apply_scene_on_mode_change:
      name: "Применять сцены в момент смены режима"
      description: "Если включено — сцена активируется сразу при наступлении дня/ночи (дополнительно, не мешает логике «первого включения»)."
      default: true
      selector:
        boolean: {}

    manual_on_auto_off_enabled:
      name: "Авто-выключение при ручном включении"
      description: "Выключать вручную включённый свет по таймауту."
      default: true
      selector:
        boolean: {}

    manual_on_day_timeout_seconds:
      name: "Таймаут ручного включения ДНЁМ (сек)"
      description: "Сколько ждать перед авто-выключением вручную включённого света днём."
      default: 900
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
          mode: box

    manual_on_night_timeout_seconds:
      name: "Таймаут ручного включения НОЧЬЮ (сек)"
      description: "Сколько ждать перед авто-выключением вручную включённого света ночью."
      default: 1800
      selector:
        number:
          min: 1
          max: 86400
          unit_of_measurement: seconds
          mode: box

    enable_day_auto_on:
      name: "Авто-включение ДНЁМ"
      description: "Позволять включать свет по движению днём."
      default: true
      selector:
        boolean: {}

    enable_day_auto_off:
      name: "Авто-выключение ДНЁМ"
      description: "Позволять выключать свет по таймауту днём."
      default: true
      selector:
        boolean: {}

    enable_night_auto_on:
      name: "Авто-включение НОЧЬЮ"
      description: "Позволять включать свет по движению ночью."
      default: true
      selector:
        boolean: {}

    enable_night_auto_off:
      name: "Авто-выключение НОЧЬЮ"
      description: "Позволять выключать свет по таймауту ночью."
      default: true
      selector:
        boolean: {}

variables:
  motion_sensors: !input motion_sensors
  target_entities: !input target_entities
  manual_entities: !input manual_entities
  night_flag: !input night_scene_pending_flag
  day_flag: !input day_scene_pending_flag

  day_timeout_seconds: !input day_timeout_seconds
  night_timeout_seconds: !input night_timeout_seconds
  manual_on_day_timeout_seconds: !input manual_on_day_timeout_seconds
  manual_on_night_timeout_seconds: !input manual_on_night_timeout_seconds

  enable_night_mode: !input enable_night_mode
  night_mode_source: !input night_mode_source
  schedule_night_start: !input schedule_night_start
  schedule_night_end: !input schedule_night_end

  sunset_offset_minutes: !input sunset_offset_minutes
  sunrise_offset_minutes: !input sunrise_offset_minutes
  sunset_offset_seconds: "{{ (sunset_offset_minutes | int) * 60 }}"
  sunrise_offset_seconds: "{{ (sunrise_offset_minutes | int) * 60 }}"

  day_scene: !input day_scene
  night_scene: !input night_scene
  apply_scene_on_mode_change: !input apply_scene_on_mode_change
  manual_on_auto_off_enabled: !input manual_on_auto_off_enabled

  enable_day_auto_on: !input enable_day_auto_on
  enable_day_auto_off: !input enable_day_auto_off
  enable_night_auto_on: !input enable_night_auto_on
  enable_night_auto_off: !input enable_night_auto_off

  # Определение ночи
  is_night_sun: "{{ states('sun.sun') == 'below_horizon' }}"
  is_night_sun_offset: >
    {% set now_ts = as_timestamp(now()) %}
    {% set next_set = state_attr('sun.sun','next_setting') %}
    {% set next_rise = state_attr('sun.sun','next_rising') %}
    {% if not next_set or not next_rise %}
      {{ states('sun.sun') == 'below_horizon' }}
    {% else %}
      {% set next_set_ts = as_timestamp(next_set) + sunset_offset_seconds %}
      {% set next_rise_ts = as_timestamp(next_rise) + sunrise_offset_seconds %}
      {% if states('sun.sun') == 'above_horizon' %}
        {{ now_ts >= next_set_ts }}
      {% else %}
        {{ now_ts <= next_rise_ts }}
      {% endif %}
    {% endif %}
  is_night_schedule: >
    {% set start = schedule_night_start %}
    {% set end = schedule_night_end %}
    {% set now_time = now().time() %}
    {% set start_time = as_datetime(strptime(start,'%H:%M:%S')).time() %}
    {% set end_time = as_datetime(strptime(end,'%H:%M:%S')).time() %}
    {% if start_time <= end_time %}
      {{ start_time <= now_time <= end_time }}
    {% else %}
      {{ now_time >= start_time or now_time <= end_time }}
    {% endif %}
  is_night: >
    {% if not enable_night_mode %}
      false
    {% elif night_mode_source == 'schedule' %}
      {{ is_night_schedule }}
    {% elif night_mode_source == 'sun_offset' %}
      {{ is_night_sun_offset }}
    {% else %}
      {{ is_night_sun }}
    {% endif %}

  motion_timeout_seconds: "{{ night_timeout_seconds if is_night else day_timeout_seconds }}"
  manual_timeout_seconds: "{{ manual_on_night_timeout_seconds if is_night else manual_on_day_timeout_seconds }}"
  allow_auto_on: "{{ enable_night_auto_on if is_night else enable_day_auto_on }}"
  allow_auto_off: "{{ enable_night_auto_off if is_night else enable_day_auto_off }}"

  # Все датчики OFF?
  all_sensors_off: >
    {{ expand(motion_sensors) | selectattr('state','eq','on') | list | count == 0 }}

mode: restart
max_exceeded: silent

trigger:
  # Движение — включение
  - id: motion_on
    platform: state
    entity_id: !input motion_sensors
    to: 'on'

  # Движение — выключение (начало таймаута)
  - id: motion_off
    platform: state
    entity_id: !input motion_sensors
    to: 'off'

  # Смена режима по солнцу
  - id: sun_rises
    platform: state
    entity_id: sun.sun
    to: 'above_horizon'

  - id: sun_sets
    platform: state
    entity_id: sun.sun
    to: 'below_horizon'

  # Смена режима по расписанию
  - id: schedule_night_start_trigger
    platform: time
    at: !input schedule_night_start

  - id: schedule_night_end_trigger
    platform: time
    at: !input schedule_night_end

  # Ручное включение света: конкретный список manual_entities
  - id: manual_on
    platform: state
    entity_id: !input manual_entities
    to: 'on'

condition: []

action:
  - choose:

      # 0) Установка флагов ожидания сцен при смене режима (ночь/день)
      - conditions:
          - condition: template
            value_template: >
              {{ (trigger.id == 'sun_sets' and night_mode_source in ['sun','sun_offset']) or
                 (trigger.id == 'schedule_night_start_trigger' and night_mode_source == 'schedule') }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ night_flag }}"
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ day_flag }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ apply_scene_on_mode_change and (night_scene is not none) }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ night_scene }}"

      - conditions:
          - condition: template
            value_template: >
              {{ (trigger.id == 'sun_rises' and night_mode_source in ['sun','sun_offset']) or
                 (trigger.id == 'schedule_night_end_trigger' and night_mode_source == 'schedule') or
                 (not enable_night_mode and trigger.id in [
                   'sun_rises','sun_sets','schedule_night_start_trigger','schedule_night_end_trigger'
                 ]) }}
        sequence:
          - service: input_boolean.turn_on
            target:
              entity_id: "{{ day_flag }}"
          - service: input_boolean.turn_off
            target:
              entity_id: "{{ night_flag }}"
          - choose:
              - conditions:
                  - condition: template
                    value_template: "{{ apply_scene_on_mode_change and (day_scene is not none) }}"
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ day_scene }}"

      # 1) Авто-включение по движению — если флаг ожидания активен, применяем соответствующую сцену ОДИН РАЗ и сбрасываем флаг
      - conditions:
          - condition: trigger
            id: motion_on
          - condition: template
            value_template: "{{ allow_auto_on }}"
        sequence:
          # Применение ночной сцены при первом включении после перехода в ночь
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ is_night and states(night_flag) == 'on' and (night_scene is not none) }}
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ night_scene }}"
                  - service: input_boolean.turn_off
                    target:
                      entity_id: "{{ night_flag }}"
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (not is_night) and states(day_flag) == 'on' and (day_scene is not none) }}
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ day_scene }}"
                  - service: input_boolean.turn_off
                    target:
                      entity_id: "{{ day_flag }}"
            default: []
          # Затем включаем целевые сущности (если сцена их не включает)
          - service: homeassistant.turn_on
            target: !input target_entities

      # 2) Выключение по таймауту (только если все датчики OFF и разрешено авто-выключение)
      - conditions:
          - condition: trigger
            id: motion_off
          - condition: template
            value_template: "{{ allow_auto_off }}"
          - condition: template
            value_template: "{{ all_sensors_off }}"
        sequence:
          - delay:
              seconds: "{{ motion_timeout_seconds | int }}"
          # Проверка отсутствия движения после таймаута
          - condition: template
            value_template: "{{ all_sensors_off }}"
          - service: homeassistant.turn_off
            target: !input target_entities

      # 3) Ручное включение — если флаг ожидания активен, применяем сцену и сбрасываем флаг, затем планируем авто-выключение
      - conditions:
          - condition: trigger
            id: manual_on
          - condition: template
            value_template: "{{ manual_on_auto_off_enabled }}"
          - condition: template
            value_template: >
              {{ (trigger.to_state.context and trigger.to_state.context.user_id) is not none }}
        sequence:
          - choose:
              - conditions:
                  - condition: template
                    value_template: >
                      {{ is_night and states(night_flag) == 'on' and (night_scene is not none) }}
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ night_scene }}"
                  - service: input_boolean.turn_off
                    target:
                      entity_id: "{{ night_flag }}"
              - conditions:
                  - condition: template
                    value_template: >
                      {{ (not is_night) and states(day_flag) == 'on' and (day_scene is not none) }}
                sequence:
                  - service: scene.turn_on
                    target:
                      entity_id: "{{ day_scene }}"
                  - service: input_boolean.turn_off
                    target:
                      entity_id: "{{ day_flag }}"
            default: []
          # Далее таймаут авто-выключения вручную включённого света
          - delay:
              seconds: "{{ manual_timeout_seconds | int }}"
          - condition: template
            value_template: "{{ all_sensors_off }}"
          - service: homeassistant.turn_off
            target: !input target_entities

    default: []
