blueprint:
  name: "DROZD - Tuya TS0042 (2 кнопки, ZHA) универсальный"
  description: >
    Универсальный blueprint для выключателя Tuya TS0042 (2 кнопки, ZHA).
    Поддерживает одиночное, двойное и долгое нажатие для левой (endpoint 1)
    и правой (endpoint 2) кнопок. Все действия настраиваются: можно вызывать
    любые сервисы, переключать сцены по кругу и т.д.
  domain: automation
  input:
    switch_ieee:
      name: "Переключатель (TS0042, ZHA)"
      description: "Выберите устройство TS0042, подключённое через ZHA"
      selector:
        device:
          integration: zha

    # ---------------- БАЗОВЫЕ ДЕЙСТВИЯ ----------------

    left_single_action:
      name: "Левая кнопка — одиночное нажатие"
      description: "Действия при одиночном нажатии левой кнопки"
      default: []
      selector:
        action: {}

    left_double_action:
      name: "Левая кнопка — двойное нажатие"
      description: "Действия при двойном нажатии левой кнопки"
      default: []
      selector:
        action: {}

    left_long_action:
      name: "Левая кнопка — долгое нажатие"
      description: "Действия при долгом нажатии левой кнопки"
      default: []
      selector:
        action: {}

    right_single_action:
      name: "Правая кнопка — одиночное нажатие"
      description: "Действия при одиночном нажатии правой кнопки"
      default: []
      selector:
        action: {}

    right_double_action:
      name: "Правая кнопка — двойное нажатие"
      description: "Действия при двойном нажатии правой кнопки"
      default: []
      selector:
        action: {}

    right_long_action:
      name: "Правая кнопка — долгое нажатие"
      description: "Действия при долгом нажатии правой кнопки"
      default: []
      selector:
        action: {}

    # ---------------- УНИВЕРСАЛЬНЫЙ ЦИКЛ СЦЕН ----------------

    cycle_enabled:
      name: "Включить перебор сцен по кругу"
      description: >
        Включает универсальный механизм переключения сцен по кругу.
        Если выключено, настройки ниже игнорируются.
      default: false
      selector:
        boolean: {}

    cycle_trigger_button:
      name: "Кнопка для перебора сцен"
      description: >
        Какой кнопкой запускать перебор сцен.
        Левая = endpoint 1, правая = endpoint 2.
      default: left
      selector:
        select:
          options:
            - label: "Левая кнопка (endpoint 1)"
              value: left
            - label: "Правая кнопка (endpoint 2)"
              value: right

    cycle_trigger_press_type:
      name: "Тип нажатия для перебора сцен"
      description: "Какой жест использовать для перебора сцен (одиночное/двойное/долгое нажатие)."
      default: double
      selector:
        select:
          options:
            - label: "Одиночное нажатие"
              value: single
            - label: "Двойное нажатие"
              value: double
            - label: "Долгое нажатие"
              value: long

    cycle_scenes:
      name: "Список сцен для перебора"
      description: >
        Выберите сцены в том порядке, в котором их нужно переключать по кругу.
        Можно указать любые сцены и любое их количество.
      default: []
      selector:
        entity:
          domain: scene
          multiple: true

    cycle_index_helper:
      name: "input_number для хранения индекса сцены"
      description: >
        Выберите helper input_number (min=0, max=N-1), который будет хранить
        текущий индекс сцены. Для разных помещений можно использовать разные helpers.
      default:
      selector:
        entity:
          domain: input_number

mode: restart
max_exceeded: silent

variables:
  switch_ieee: !input switch_ieee
  cycle_enabled: !input cycle_enabled
  cycle_trigger_button: !input cycle_trigger_button
  cycle_trigger_press_type: !input cycle_trigger_press_type
  cycle_scenes: !input cycle_scenes
  cycle_index_helper: !input cycle_index_helper

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_ieee: !input switch_ieee

action:
  - variables:
      endpoint_id: "{{ trigger.event.data.endpoint_id | int }}"
      command: "{{ trigger.event.data.command }}"
      press_type: >
        {% if command == 'remote_button_short_press' %}
          single
        {% elif command == 'remote_button_double_press' %}
          double
        {% elif command == 'remote_button_long_press' %}
          long
        {% else %}
          unknown
        {% endif %}
      button: >
        {% if endpoint_id == 1 %}
          left
        {% elif endpoint_id == 2 %}
          right
        {% else %}
          unknown
        {% endif %}

  - choose:

      # ---------- БАЗОВЫЕ ДЕЙСТВИЯ ДЛЯ КНОПОК ----------

      # Левая кнопка
      - conditions:
          - condition: template
            value_template: "{{ button == 'left' and press_type == 'single' }}"
        sequence: !input left_single_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'left' and press_type == 'double' }}"
        sequence: !input left_double_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'left' and press_type == 'long' }}"
        sequence: !input left_long_action

      # Правая кнопка
      - conditions:
          - condition: template
            value_template: "{{ button == 'right' and press_type == 'single' }}"
        sequence: !input right_single_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'right' and press_type == 'double' }}"
        sequence: !input right_double_action

      - conditions:
          - condition: template
            value_template: "{{ button == 'right' and press_type == 'long' }}"
        sequence: !input right_long_action

      # ---------- УНИВЕРСАЛЬНЫЙ ПЕРЕБОР СЦЕН ----------

      - conditions:
          - condition: template
            value_template: >
              {{ cycle_enabled
                 and button == cycle_trigger_button
                 and press_type == cycle_trigger_press_type
                 and (cycle_scenes.entity_id | count) > 0
                 and cycle_index_helper is not none }}
        sequence:
          - variables:
              scenes_list: "{{ cycle_scenes.entity_id }}"
              max_index: "{{ (scenes_list | count) - 1 }}"
              current_index: "{{ states(cycle_index_helper) | int(0) }}"
              next_index: >
                {% if current_index >= max_index %}
                  0
                {% else %}
                  {{ current_index + 1 }}
                {% endif %}
          - service: scene.turn_on
            target:
              entity_id: "{{ scenes_list[next_index | int] }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ cycle_index_helper }}"
            data:
              value: "{{ next_index }}"
