blueprint:
  name: "DROZD Будильник спальни (шторы + мягкий свет) v1.0"
  description: >
    Будильник для спальни с раздельными настройками для будней и выходных.

  domain: automation

  input:
    # --- Время будильника ---
    weekday_time:
      name: Время будильника будни
      description: >
        понедельник–пятница
      default: "07:00:00"
      selector:
        time:

    weekend_time:
      name: Время будильника выходные
      description: >
        суббота–воскресенье
      default: "09:30:00"
      selector:
        time:

    # --- Режим пробуждения ---
    weekday_soft_mode:
      name: Мягкое пробуждение в будни
      description: >
        Если включено — в будни мягкое пробуждение, иначе быстрое.
      default: true
      selector:
        boolean:

    weekend_soft_mode:
      name: Мягкое пробуждение в выходные
      description: >
        Если включено — в выходные мягкое пробуждение, иначе быстрое.
      default: true
      selector:
        boolean:

    # --- Устройства ---
    bedroom_light:
      name: Свет в спальне
      description: >
        Диммируемая лампа/светильник.
      selector:
        entity:
          domain: light

    bedroom_cover:
      name: Шторы / жалюзи спальни
      description: >
        Мотор для подъёма/опускания штор.
      selector:
        entity:
          domain: cover

    bedroom_switch:
      name: Дополнительный выключатель (опционально)
      description: >
        Например, бра или розетка. Можно оставить пустым.
      default: ""
      selector:
        entity:
          domain: switch
          multiple: false
          include_entities: []

    # --- Параметры мягкого пробуждения ---
    soft_start_brightness:
      name: Начальная яркость (мягкое пробуждение), %
      default: 15
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
          mode: slider

    soft_mid_brightness:
      name: Средняя яркость (мягкое пробуждение), %
      default: 30
      selector:
        number:
          min: 10
          max: 80
          unit_of_measurement: "%"
          mode: slider

    soft_final_brightness:
      name: Итоговая яркость (мягкое пробуждение), %
      default: 60
      selector:
        number:
          min: 30
          max: 100
          unit_of_measurement: "%"
          mode: slider

    soft_step_delay:
      name: Пауза между шагами (мягкое пробуждение), мин
      default: 2
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: "мин"
          mode: slider

    # --- Вечер: опускание штор ---
    close_blinds_use_sun:
      name: Опускать шторы по солнцу
      description: >
        Если включено — закрываем шторы по закату + оффсет.
        Если выключено — по фиксированному времени.
      default: true
      selector:
        boolean:

    blinds_fixed_time:
      name: Время опускания штор (фиксированное)
      description: >
        Используется, если опция "опускать по солнцу" выключена.
      default: "20:00:00"
      selector:
        time:

    blinds_sunset_offset:
      name: Оффсет от заката для опускания штор
      description: >
        Формат HH:MM:SS.
        Отрицательное значение — до заката, положительное — после.
        Пример: "-00:20:00" — за 20 минут до заката.
      default: "-00:20:00"
      selector:
        text:

mode: restart
max_exceeded: silent

variables:
  v_weekday_time: !input weekday_time
  v_weekend_time: !input weekend_time

  v_weekday_soft_mode: !input weekday_soft_mode
  v_weekend_soft_mode: !input weekend_soft_mode

  v_light: !input bedroom_light
  v_cover: !input bedroom_cover
  v_switch: !input bedroom_switch

  v_soft_start_brightness: !input soft_start_brightness
  v_soft_mid_brightness: !input soft_mid_brightness
  v_soft_final_brightness: !input soft_final_brightness
  v_soft_step_delay: !input soft_step_delay

  v_close_blinds_use_sun: !input close_blinds_use_sun
  v_blinds_fixed_time: !input blinds_fixed_time
  v_blinds_sunset_offset: !input blinds_sunset_offset

trigger:
  # Будильник: будни
  - id: weekday_alarm
    platform: time
    at: "{{ v_weekday_time }}"

  # Будильник: выходные
  - id: weekend_alarm
    platform: time
    at: "{{ v_weekend_time }}"

  # Опускание штор по фиксированному времени
  - id: blinds_close_fixed
    platform: time
    at: "{{ v_blinds_fixed_time }}"

  # Опускание штор по солнцу
  - id: blinds_close_sun
    platform: sun
    event: sunset
    offset: "{{ v_blinds_sunset_offset }}"

condition: []

action:
  - choose:
      # -------------------------
      # 1. Будильник: будние дни
      # -------------------------
      - conditions:
          - condition: trigger
            id: weekday_alarm
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - choose:
              # Мягкое пробуждение (будни)
              - conditions:
                  - condition: template
                    value_template: "{{ v_weekday_soft_mode }}"
                sequence:
                  - alias: "Мягкое пробуждение (будни)"
                    sequence:
                      # 1. Низкая яркость
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_start_brightness | int }}"
                          transition: 30

                      # 2. Пауза и средняя яркость
                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_mid_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      # 3. Пауза и итоговая яркость
                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_final_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      # 4. Поднимаем шторы
                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      # 5. Опционально включаем выключатель
                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"

              # Быстрое пробуждение (будни)
              - conditions:
                  - condition: template
                    value_template: "{{ not v_weekday_soft_mode }}"
                sequence:
                  - alias: "Быстрое пробуждение (будни)"
                    sequence:
                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: 80
                          transition: 10

                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"
            default: []

      # -------------------------
      # 2. Будильник: выходные
      # -------------------------
      - conditions:
          - condition: trigger
            id: weekend_alarm
          - condition: time
            weekday:
              - sat
              - sun
        sequence:
          - choose:
              # Мягкое пробуждение (выходные)
              - conditions:
                  - condition: template
                    value_template: "{{ v_weekend_soft_mode }}"
                sequence:
                  - alias: "Мягкое пробуждение (выходные)"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_start_brightness | int }}"
                          transition: 30

                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_mid_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_final_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"

              # Быстрое пробуждение (выходные)
              - conditions:
                  - condition: template
                    value_template: "{{ not v_weekend_soft_mode }}"
                sequence:
                  - alias: "Быстрое пробуждение (выходные)"
                    sequence:
                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: 80
                          transition: 10

                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"
            default: []

      # -------------------------
      # 3. Опускание штор по фиксированному времени
      # -------------------------
      - conditions:
          - condition: trigger
            id: blinds_close_fixed
          - condition: template
            value_template: "{{ not v_close_blinds_use_sun }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ v_cover }}"

      # -------------------------
      # 4. Опускание штор по солнцу
      # -------------------------
      - conditions:
          - condition: trigger
            id: blinds_close_sun
          - condition: template
            value_template: "{{ v_close_blinds_use_sun }}"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ v_cover }}"
    default: []
