blueprint:
  name: "DROZD Будильник спальни (шторы + мягкий свет) v1.0"
  description: >
    Будильник для спальни с разделением на будни и выходные.
    Время будильника вводится текстом (HH:MM:SS) в настройках blueprint.
    Управление режимом будильника и типом пробуждения — через input_boolean и input_select.
    Опускание штор — по фиксированному времени или по солнцу (закат + оффсет).

  domain: automation

  input:
    # --- Управление будильником ---
    alarm_enabled:
      name: Включен ли будильник
      description: >
        input_boolean — общий включатель будильника.
      selector:
        entity:
          domain: input_boolean

    weekday_mode:
      name: Режим пробуждения (будни)
      description: >
        input_select с вариантами сценариев пробуждения (минимум 2).
      selector:
        entity:
          domain: input_select

    weekend_mode:
      name: Режим пробуждения (выходные)
      description: >
        input_select с вариантами сценариев пробуждения (минимум 2).
      selector:
        entity:
          domain: input_select

    mode_soft_label:
      name: Название опции "мягкое пробуждение"
      description: >
        Значение из input_select, соответствующее мягкому пробуждению.
      default: "Мягкое пробуждение"
      selector:
        text:

    mode_fast_label:
      name: Название опции "быстрое пробуждение"
      description: >
        Значение из input_select, соответствующее быстрому пробуждению.
      default: "Быстрое пробуждение"
      selector:
        text:

    # --- Время будильника (строкой) ---
    weekday_time_str:
      name: Время будильника (будни), HH:MM:SS
      description: >
        Вводи время в формате 24ч HH:MM:SS, например 07:00:00.
      default: "07:00:00"
      selector:
        text:

    weekend_time_str:
      name: Время будильника (выходные), HH:MM:SS
      description: >
        Вводи время в формате 24ч HH:MM:SS, например 09:00:00.
      default: "09:00:00"
      selector:
        text:

    # --- Свет и шторы ---
    bedroom_light:
      name: Свет в спальне
      selector:
        entity:
          domain: light

    bedroom_cover:
      name: Шторы / жалюзи спальни
      selector:
        entity:
          domain: cover

    bedroom_switch:
      name: Дополнительный выключатель (опционально)
      description: >
        Например, бра или розетка. Можно не указывать.
      default: ""
      selector:
        entity:
          domain: switch
          multiple: false
          include_entities: []

    # --- Параметры мягкого пробуждения ---
    soft_start_brightness:
      name: Начальная яркость (мягкое пробуждение), %
      default: 5
      selector:
        number:
          min: 1
          max: 50
          unit_of_measurement: "%"
          mode: slider

    soft_mid_brightness:
      name: Средняя яркость (мягкое пробуждение), %
      default: 30
      selector:
        number:
          min: 10
          max: 80
          unit_of_measurement: "%"
          mode: slider

    soft_final_brightness:
      name: Итоговая яркость (мягкое пробуждение), %
      default: 60
      selector:
        number:
          min: 30
          max: 100
          unit_of_measurement: "%"
          mode: slider

    soft_step_delay:
      name: Пауза между шагами (мягкое пробуждение), мин
      default: 3
      selector:
        number:
          min: 1
          max: 30
          unit_of_measurement: "мин"
          mode: slider

    # --- Вечер: опускание штор ---
    blinds_fixed_time_str:
      name: Время опускания штор (фиксированное), HH:MM:SS
      description: >
        Например 22:30:00.
      default: "22:30:00"
      selector:
        text:

    blinds_sun_mode:
      name: Режим "шторы по солнцу"
      description: >
        input_boolean. Если включен — закрываем шторы по закату плюс оффсет.
      selector:
        entity:
          domain: input_boolean

    blinds_sunset_offset:
      name: Оффсет от заката для опускания штор
      description: >
        Формат HH:MM:SS.
        Отрицательное значение — до заката, положительное — после.
        Пример: "-00:20:00" — за 20 минут до заката.
      default: "-00:20:00"
      selector:
        text:

mode: restart
max_exceeded: silent

variables:
  v_alarm_enabled: !input alarm_enabled
  v_weekday_mode: !input weekday_mode
  v_weekend_mode: !input weekend_mode
  v_mode_soft_label: !input mode_soft_label
  v_mode_fast_label: !input mode_fast_label

  v_weekday_time_str: !input weekday_time_str
  v_weekend_time_str: !input weekend_time_str
  v_blinds_fixed_time_str: !input blinds_fixed_time_str

  v_light: !input bedroom_light
  v_cover: !input bedroom_cover
  v_switch: !input bedroom_switch

  v_soft_start_brightness: !input soft_start_brightness
  v_soft_mid_brightness: !input soft_mid_brightness
  v_soft_final_brightness: !input soft_final_brightness
  v_soft_step_delay: !input soft_step_delay

  v_blinds_sun_mode: !input blinds_sun_mode
  v_blinds_sunset_offset: !input blinds_sunset_offset

trigger:
  # Будильник: будни (по строке времени)
  - id: weekday_alarm
    platform: time
    at: "{{ v_weekday_time_str }}"

  # Будильник: выходные
  - id: weekend_alarm
    platform: time
    at: "{{ v_weekend_time_str }}"

  # Опускание штор по фиксированному времени
  - id: blinds_close_fixed
    platform: time
    at: "{{ v_blinds_fixed_time_str }}"

  # Опускание штор по солнцу (закат + оффсет)
  - id: blinds_close_sun
    platform: sun
    event: sunset
    offset: "{{ v_blinds_sunset_offset }}"

condition: []

action:
  - choose:
      # -------------------------
      # 1. Будильник: будние дни
      # -------------------------
      - conditions:
          - condition: trigger
            id: weekday_alarm
          - condition: state
            entity_id: !input alarm_enabled
            state: "on"
          - condition: time
            weekday:
              - mon
              - tue
              - wed
              - thu
              - fri
        sequence:
          - choose:
              # Мягкое пробуждение (будни)
              - conditions:
                  - condition: template
                    value_template: >
                      {{ states(v_weekday_mode) == v_mode_soft_label }}
                sequence:
                  - alias: "Мягкое пробуждение (будни)"
                    sequence:
                      # 1. Низкая яркость
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_start_brightness | int }}"
                          transition: 30

                      # 2. Пауза и средняя яркость
                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_mid_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      # 3. Пауза и итоговая яркость
                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_final_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      # 4. Поднимаем шторы
                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      # 5. Опционально включаем выключатель
                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"

              # Быстрое пробуждение (будни)
              - conditions:
                  - condition: template
                    value_template: >
                      {{ states(v_weekday_mode) == v_mode_fast_label }}
                sequence:
                  - alias: "Быстрое пробуждение (будни)"
                    sequence:
                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: 80
                          transition: 10

                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"
            default: []

      # -------------------------
      # 2. Будильник: выходные
      # -------------------------
      - conditions:
          - condition: trigger
            id: weekend_alarm
          - condition: state
            entity_id: !input alarm_enabled
            state: "on"
          - condition: time
            weekday:
              - sat
              - sun
        sequence:
          - choose:
              # Мягкое пробуждение (выходные)
              - conditions:
                  - condition: template
                    value_template: >
                      {{ states(v_weekend_mode) == v_mode_soft_label }}
                sequence:
                  - alias: "Мягкое пробуждение (выходные)"
                    sequence:
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_start_brightness | int }}"
                          transition: 30

                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_mid_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      - delay:
                          minutes: "{{ v_soft_step_delay | int }}"
                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: "{{ v_soft_final_brightness | int }}"
                          transition: "{{ (v_soft_step_delay | int) * 60 }}"

                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"

              # Быстрое пробуждение (выходные)
              - conditions:
                  - condition: template
                    value_template: >
                      {{ states(v_weekend_mode) == v_mode_fast_label }}
                sequence:
                  - alias: "Быстрое пробуждение (выходные)"
                    sequence:
                      - service: cover.open_cover
                        target:
                          entity_id: "{{ v_cover }}"

                      - service: light.turn_on
                        target:
                          entity_id: "{{ v_light }}"
                        data:
                          brightness_pct: 80
                          transition: 10

                      - if:
                          - condition: template
                            value_template: "{{ v_switch != '' }}"
                        then:
                          - service: switch.turn_on
                            target:
                              entity_id: "{{ v_switch }}"
            default: []

      # -------------------------
      # 3. Опускание штор по фиксированному времени
      # -------------------------
      - conditions:
          - condition: trigger
            id: blinds_close_fixed
          # Только если НЕ режим по солнцу
          - condition: state
            entity_id: !input blinds_sun_mode
            state: "off"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ v_cover }}"

      # -------------------------
      # 4. Опускание штор по солнцу
      # -------------------------
      - conditions:
          - condition: trigger
            id: blinds_close_sun
          # Только если режим по солнцу включен
          - condition: state
            entity_id: !input blinds_sun_mode
            state: "on"
        sequence:
          - service: cover.close_cover
            target:
              entity_id: "{{ v_cover }}"
    default: []
