blueprint:
  name: DROZD Scene Switch Tuya TS0042
  description: Автоматизация для 2 button Scene Switch Tuya TS0042
  domain: automation
  input:
    ieee_address:
      name: IEEE устройства
      description: IEEE вашего Tuya TS0042
      selector:
        text:
    light_left:
      name: Левая клавиша одиночное нажатие
      selector:
        entity:
          domain: light
    light_right:
      name: Правая клавиша одиночное нажатие
      selector:
        entity:
          domain: light
    scenes_left:
      name: Сцены левой клавиши - двойное нажатие (input_select)
      selector:
        entity:
          domain: input_select
    scenes_right:
      name: Сцены правой клавиши - двойное нажатие (input_select)
      selector:
        entity:
          domain: input_select
    boolean_left:
      name: Долгое нажатие левая клавиша (input_boolean)
      selector:
        entity:
          domain: input_boolean
    boolean_right:
      name: Долгое нажатие правая клавиша (input_boolean)
      selector:
        entity:
          domain: input_boolean

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_ieee == '70:c5:9c:ff:fe:36:5a:da' and
         trigger.event.data.command in ['remote_button_short_press', 'remote_button_double_press', 'remote_button_long_press'] and
         trigger.event.data.endpoint_id in [1, 2] }}

action:
  - choose:
      # Левая клавиша — одиночное нажатие
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_short_press' }}
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_left

      # Левая клавиша — двойное нажатие (только переключить)
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_double_press' }}
        sequence:
          - service: input_select.select_next
            target:
              entity_id: !input scenes_left

      # Левая клавиша — долгое нажатие
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'remote_button_long_press' }}
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: !input boolean_left

      # Правая клавиша — одиночное нажатие
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_short_press' }}
        sequence:
          - service: light.toggle
            target:
              entity_id: !input light_right

      # Правая клавиша — двойное нажатие (только переключить)
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_double_press' }}
        sequence:
          - service: input_select.select_next
            target:
              entity_id: !input scenes_right

      # Правая клавиша — долгое нажатие
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'remote_button_long_press' }}
        sequence:
          - service: input_boolean.toggle
            target:
              entity_id: !input boolean_right
