blueprint:
  name: "DROZD Tuya TS0042 (ZHA) – простые действия и перебор сцен"
  description: >
    Для переключателя Tuya TS0042 (2 кнопки, ZHA, zha_event).
    Использует device_id (не нужен IEEE).
    Позволяет:
      - задать простые действия для левой/правой кнопки (single/double/long);
      - независимо настроить перебор сцен по кругу:
          * отдельный набор сцен и input_number для левой кнопки;
          * отдельный набор сцен и input_number для правой кнопки;
          * отдельный жест (single/double/long) для запуска цикла.

  domain: automation

  input:
    zha_device:
      name: "Переключатель (TS0042, ZHA)"
      description: "Выберите устройство TS0042, подключённое через ZHA"
      selector:
        device:
          integration: zha

    # ---------- ПРОСТЫЕ ДЕЙСТВИЯ: ЛЕВАЯ КНОПКА ----------
    left_single_action:
      name: "Левая кнопка – одиночное нажатие"
      default: []
      selector:
        action: {}

    left_double_action:
      name: "Левая кнопка – двойное нажатие"
      default: []
      selector:
        action: {}

    left_long_action:
      name: "Левая кнопка – долгое нажатие"
      default: []
      selector:
        action: {}

    # ---------- ПРОСТЫЕ ДЕЙСТВИЯ: ПРАВАЯ КНОПКА ----------
    right_single_action:
      name: "Правая кнопка – одиночное нажатие"
      default: []
      selector:
        action: {}

    right_double_action:
      name: "Правая кнопка – двойное нажатие"
      default: []
      selector:
        action: {}

    right_long_action:
      name: "Правая кнопка – долгое нажатие"
      default: []
      selector:
        action: {}

    # ---------- ПЕРЕБОР СЦЕН: ЛЕВАЯ КНОПКА ----------
    left_cycle_enabled:
      name: "Перебор сцен (левая кнопка)"
      description: "Включить переключение заданных сцен по кругу для левой кнопки."
      default: false
      selector:
        boolean: {}

    left_cycle_press_type:
      name: "Жест для перебора сцен (левая кнопка)"
      description: "Какое нажатие левой кнопки использовать для перебора сцен."
      default: double
      selector:
        select:
          options:
            - label: "Одиночное нажатие"
              value: single
            - label: "Двойное нажатие"
              value: double
            - label: "Долгое нажатие"
              value: long

    left_cycle_scenes:
      name: "Сцены для перебора (левая кнопка)"
      description: "Список сцен, которые будут переключаться по кругу левой кнопкой."
      default: []
      selector:
        entity:
          domain: scene
          multiple: true

    left_cycle_index_helper:
      name: "input_number индекса сцен (левая кнопка)"
      description: "input_number (min=0, max=N-1), хранящий индекс текущей сцены левой кнопки."
      default:
      selector:
        entity:
          domain: input_number

    # ---------- ПЕРЕБОР СЦЕН: ПРАВАЯ КНОПКА ----------
    right_cycle_enabled:
      name: "Перебор сцен (правая кнопка)"
      description: "Включить переключение заданных сцен по кругу для правой кнопки."
      default: false
      selector:
        boolean: {}

    right_cycle_press_type:
      name: "Жест для перебора сцен (правая кнопка)"
      description: "Какое нажатие правой кнопки использовать для перебора сцен."
      default: double
      selector:
        select:
          options:
            - label: "Одиночное нажатие"
              value: single
            - label: "Двойное нажатие"
              value: double
            - label: "Долгое нажатие"
              value: long

    right_cycle_scenes:
      name: "Сцены для перебора (правая кнопка)"
      description: "Список сцен, которые будут переключаться по кругу правой кнопкой."
      default: []
      selector:
        entity:
          domain: scene
          multiple: true

    right_cycle_index_helper:
      name: "input_number индекса сцен (правая кнопка)"
      description: "input_number (min=0, max=N-1), хранящий индекс текущей сцены правой кнопки."
      default:
      selector:
        entity:
          domain: input_number

mode: restart
max_exceeded: silent

variables:
  zha_device: !input zha_device

  left_cycle_enabled: !input left_cycle_enabled
  left_cycle_press_type: !input left_cycle_press_type
  left_cycle_scenes: !input left_cycle_scenes
  left_cycle_index_helper: !input left_cycle_index_helper

  right_cycle_enabled: !input right_cycle_enabled
  right_cycle_press_type: !input right_cycle_press_type
  right_cycle_scenes: !input right_cycle_scenes
  right_cycle_index_helper: !input right_cycle_index_helper

trigger:
  - platform: event
    event_type: zha_event
    event_data:
      device_id: !input zha_device

action:
  - variables:
      endpoint_id: "{{ trigger.event.data.endpoint_id | int }}"
      command: "{{ trigger.event.data.command }}"
      press_type: >
        {% if command == 'remote_button_short_press' %}
          single
        {% elif command == 'remote_button_double_press' %}
          double
        {% elif command == 'remote_button_long_press' %}
          long
        {% else %}
          unknown
        {% endif %}

  - choose:

      # ========== ЛЕВАЯ КНОПКА (endpoint_id = 1) – ПРОСТЫЕ ДЕЙСТВИЯ ==========

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 1 and press_type == 'single' }}"
        sequence: !input left_single_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 1 and press_type == 'double' }}"
        sequence: !input left_double_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 1 and press_type == 'long' }}"
        sequence: !input left_long_action

      # ========== ЛЕВАЯ КНОПКА – ПЕРЕБОР СЦЕН ==========

      - conditions:
          - condition: template
            value_template: >
              {{ endpoint_id == 1
                 and left_cycle_enabled
                 and press_type == left_cycle_press_type
                 and left_cycle_scenes is not none
                 and (left_cycle_scenes | count) > 0
                 and left_cycle_index_helper is not none }}
        sequence:
          - variables:
              scenes: "{{ left_cycle_scenes }}"
              max_index: "{{ (scenes | count) - 1 }}"
              current_index: "{{ states(left_cycle_index_helper) | int(0) }}"
              next_index: >
                {% if current_index >= max_index %}
                  0
                {% else %}
                  {{ current_index + 1 }}
                {% endif %}
              next_scene: "{{ scenes[next_index | int] }}"
          - service: scene.turn_on
            target:
              entity_id: "{{ next_scene }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ left_cycle_index_helper }}"
            data:
              value: "{{ next_index }}"

      # ========== ПРАВАЯ КНОПКА (endpoint_id = 2) – ПРОСТЫЕ ДЕЙСТВИЯ ==========

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 2 and press_type == 'single' }}"
        sequence: !input right_single_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 2 and press_type == 'double' }}"
        sequence: !input right_double_action

      - conditions:
          - condition: template
            value_template: "{{ endpoint_id == 2 and press_type == 'long' }}"
        sequence: !input right_long_action

      # ========== ПРАВАЯ КНОПКА – ПЕРЕБОР СЦЕН ==========

      - conditions:
          - condition: template
            value_template: >
              {{ endpoint_id == 2
                 and right_cycle_enabled
                 and press_type == right_cycle_press_type
                 and right_cycle_scenes is not none
                 and (right_cycle_scenes | count) > 0
                 and right_cycle_index_helper is not none }}
        sequence:
          - variables:
              scenes: "{{ right_cycle_scenes }}"
              max_index: "{{ (scenes | count) - 1 }}"
              current_index: "{{ states(right_cycle_index_helper) | int(0) }}"
              next_index: >
                {% if current_index >= max_index %}
                  0
                {% else %}
                  {{ current_index + 1 }}
                {% endif %}
              next_scene: "{{ scenes[next_index | int] }}"
          - service: scene.turn_on
            target:
              entity_id: "{{ next_scene }}"
          - service: input_number.set_value
            target:
              entity_id: "{{ right_cycle_index_helper }}"
            data:
              value: "{{ next_index }}"
