blueprint:
  name: Test Blueprint
  domain: automation
  input:
    # Вместо !input используйте фиктивное значение
    input_select_entity:
      name: Input Select
      selector:
        entity:
          domain: input_select

# триггер
trigger:
  - platform: event
    event_type: zha_event

# условие
condition:
  - condition: template
    value_template: >
      {{ true }}

# действия
action:
  - service: input_select.select_next
    target:
      entity_id: input_select.test_entity

  - service: scene.turn_on
    target:
      entity_id: scene.test_scene

  - delay: "00:00:01"

  - service: input_select.select_option
    
      entity_id: input_select.test_entity
      option: "test_option"






