blueprint:
  name: Tuya TS0042 Multi-Device Scene Switch ZHA with 8 Scenes (Validation copy)
  description: Проверка YAML без тегов !input для внешнего валидатора
  domain: automation
  input:
    devices:
      name: Устройства IEEE
      description: Список IEEE адресов через запятую
      selector:
        text:
          multiline: true
    input_select_entity:
      name: Input Select
      selector:
        entity:
          domain: input_select
    scene_1:
      name: Сцена 1
      selector:
        entity:
          domain: scene
    scene_2:
      name: Сцена 2
      selector:
        entity:
          domain: scene
    scene_3:
      name: Сцена 3
      selector:
        entity:
          domain: scene
    scene_4:
      name: Сцена 4
      selector:
        entity:
          domain: scene
    scene_5:
      name: Сцена 5
      selector:
        entity:
          domain: scene
    scene_6:
      name: Сцена 6
      selector:
        entity:
          domain: scene
    scene_7:
      name: Сцена 7
      selector:
        entity:
          domain: scene
    scene_8:
      name: Сцена 8
      selector:
        entity:
          domain: scene

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_ieee in [d.strip() for d in blueprint.devices.split(',')] and
         trigger.event.data.command in ['short', 'double', 'long'] and
         trigger.event.data.endpoint_id in [1, 2] }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'double' }}
        sequence:
          - service: input_select.select_next
            target:
              entity_id: input_select.test_entity

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'short' }}
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.test_scene_1

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 1 and trigger.event.data.command == 'long' }}
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.test_scene_4

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'double' }}
        sequence:
          - service: input_select.select_previous
            target:
              entity_id: input_select.test_entity

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'short' }}
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.test_scene_2

      - conditions:
          - condition: template
            value_template: >
              {{ trigger.event.data.endpoint_id == 2 and trigger.event.data.command == 'long' }}
        sequence:
          - service: scene.turn_on
            target:
              entity_id: scene.test_scene_3

  - delay: "00:00:01"

  - service: input_select.select_option
    
      entity_id: input_select.test_entity
      option: "test_option"







