blueprint:
  name: Tuya TS0042 Scene Switch with Cycle and Dual Action
  description: Универсальный Blueprint для TS0042 с переключением сцен по двойному нажатию и выбором устройства
  domain: automation
  input:
    device:
      name: TS0042 Switch
      description: Устройство Tuya TS0042
      selector:
        device:
          integration: zha  # или zigbee2mqtt
          manufacturer: Tuya
          model: TS0042
    input_select_entity:
      name: Input Select
      description: Input_select с сценами для переключения
      selector:
        entity:
          domain: input_select
    scene_1:
      name: Сцена 1
      description: Первая сцена
      selector:
        entity:
          domain: scene
    scene_2:
      name: Сцена 2
      description: Вторая сцена
      selector:
        entity:
          domain: scene
    scene_3:
      name: Сцена 3
      description: Третья сцена
      selector:
        entity:
          domain: scene

trigger:
  - platform: event
    event_type: zha_event  # или zigbee2mqtt_event
    event_
      device_ieee: !input device
      command: double
      endpoint_id: 1
  - platform: event
    event_type: zha_event
    event_
      device_ieee: !input device
      command: double
      endpoint_id: 2

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
        sequence:
          - service: input_select.select_next
            target:
              entity_id: !input input_select_entity

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 }}"
        sequence:
          - service: input_select.select_previous
            target:
              entity_id: !input input_select_entity

  - delay: "00:00:01"

  - service: scene.turn_on
    target:
      entity_id: >
        {% set current = states(input_select_entity).state %}
        {% set options = state_attr(input_select_entity, 'options') %}
        {% set current_index = options.index(current) if current in options else 0 %}
        {% set scenes = [ 'scene.scene_1', 'scene.scene_2', 'scene.scene_3' ] %}
        {{ scenes[current_index] }}
