blueprint:
  name: Tuya TS0042 Multi-Device Scene Switch with ZHA Integration
  description: Универсальный blueprint для TS0042 с выбором устройств по IEEE и циклическим переключением сцен. Предназначен для интеграции ZHA.
  domain: automation
  input:
    devices:
      name: Устройства TS0042 (IEEE адреса)
      description: Список IEEE адресов устройств Tuya TS0042 (через запятую или список)
      selector:
        text:
          multiline: true
    input_select_entity:
      name: Input Select для выбора сцены
      description: Input_select с перечисленными сценами
      selector:
        entity:
          domain: input_select
    scenes:
      name: Сцены
      description: Список сцен для циклического переключения
      selector:
        entity:
          domain: scene
          multiple: true

trigger:
  - platform: event
    event_type: zha_event

condition:
  - condition: template
    value_template: >
      {{ trigger.event.data.device_ieee in [d.strip() for d in (blueprint.devices.split(','))] and
         trigger.event.data.command == 'double' and
         trigger.event.data.endpoint_id in [1,2] }}

action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 1 }}"
        sequence:
          - service: input_select.select_next
            target:
              entity_id: !input input_select_entity

      - conditions:
          - condition: template
            value_template: "{{ trigger.event.data.endpoint_id == 2 }}"
        sequence:
          - service: input_select.select_previous
            target:
              entity_id: !input input_select_entity

  - delay: '00:00:01'

  - service: scene.turn_on
    target:
      entity_id: >
        {% set current = states(!input input_select_entity).state %}
        {% set options = state_attr(!input input_select_entity, 'options') %}
        {% set current_index = options.index(current) if current in options else 0 %}
        {% set scenes = [s.entity_id for s in expand(!input scenes)] %}
        {{ scenes[current_index] }}

